# Generated by Django 5.0.4 on 2025-04-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="trending",
            field=models.BooleanField(default=False),
        ),
    ]
