# Generated by Django 5.0.4 on 2025-04-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_product_discount_product_featured_product_trending"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
    ]
