# Generated by Django 5.0.4 on 2025-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_productimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                default="product_images/default.jpg", upload_to="product_images/"
            ),
        ),
    ]
